# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # update_rate specifies how often (in Hz) the controllers should be updated.
 

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    grip_action_controller:
      type: position_controllers/GripperActionController
 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
 
# Define the parameters for each controller
arm_controller:
  ros__parameters:
    joints:
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
      - link4_to_link5
      - link5_to_link6
      - link6_to_link6flange
 
    command_interfaces:
      - position
     
    state_interfaces:
      - position
 
    open_loop_control: true
 
    allow_integration_in_goal_trajectories: true

grip_action_controller:
  ros__parameters:
    joint: gripper_controller
 