<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="camera_x"  value="0.01"/>
    <xacro:property name="camera_y"  value="0.08"/>
    <xacro:property name="camera_z"  value="0.01"/>

    <xacro:property name="camera_joint_x"  value="${car_length / 2 - 0.01}"/>
    <xacro:property name="camera_joint_y"  value="0"/>
    <xacro:property name="camera_joint_z"  value="${car_height / 2 + camera_z / 2}"/>

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/> <!-- 设定摄像头的质量 -->
            <origin xyz="0 0 0"/>
            <inertia ixx="0.000001" ixy="0.0" ixz="0.0"
                     iyy="0.000001" iyz="0.0"
                     izz="0.000002"/>
        </inertial>

    </link>
    <joint name="camera_to_base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z}" rpy="0.0 -0.1 0.0"/>
    </joint>
    
    <gazebo reference="camera">
        <sensor name="rgb_camera" type="camera">
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <camera>
                <horizontal_fov>1.25</horizontal_fov>
                <image>
                    <width>320</width>
                    <height>240</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
                <camera_name>rgb_camera</camera_name>
                <image_topic_name>/camera/image_raw</image_topic_name>
                <camera_info_topic_name>/camera/camera_info</camera_info_topic_name>
                <frame_name>camera_optical_frame</frame_name>
            </plugin>
        </sensor>
        <material>Gazebo/Red</material>
    </gazebo>

</robot>