arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  position_only_ik: false
  kinematics_solver_attempts: 10

# Typically we don't need a complex kinematics solver for the gripper. This is for demonstration purposes only.  

gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  position_only_ik: false
  kinematics_solver_attempts: 10
  

arm_with_gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  position_only_ik: false
  kinematics_solver_attempts: 10