<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="PI"  value="3.1415926"/>

    <xacro:property name="car_length"  value="0.35"/>
    <xacro:property name="car_width"  value="0.2"/>
    <xacro:property name="car_height"  value="0.07"/>

    <xacro:property name="wheel_radius"  value="0.025"/>
    <xacro:property name="wheel_length"  value="0.02"/>

    <xacro:property name="wheel_joint_x" value="${car_length/3.5}"/>
    <xacro:property name="wheel_joint_y" value="${car_width / 2}"/>
    <xacro:property name="wheel_joint_z" value="${-(car_height / 2 + distance - wheel_radius)}"/>

    <xacro:property name="distance"  value="0.015"/>

    <material name="yellow">
        <color rgba="0.9 0.6 0.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <link name="base_footprint">
        <visual>
                <geometry>
                    <sphere radius="0.001"/>
                </geometry>
        </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <box size="${car_length} ${car_width} ${car_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.002" ixy="0.0" ixz="0.0"
                     iyy="0.002" iyz="0.0"
                     izz="0.004"/>
        </inertial>
    </link>

    <joint name="base_link_to_base_footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${car_height/2 + distance}" rpy="0.0 0.0 0.0"/>
    </joint>

    <xacro:macro name="wheel_func" params="link_name front_flag left_flag">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="black"/>
                <origin rpy="${PI / 2} 0.0 0.0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin rpy="${PI / 2} 0.0 0.0"/>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                         iyy="0.0001" iyz="0.0"
                         izz="0.0002"/>
            </inertial>
        </link>
        <joint name="${link_name}_to_base_link" type="continuous">
            <parent link="base_link"/>
            <child link="${link_name}"/>
            <origin xyz="${wheel_joint_x * front_flag} ${wheel_joint_y * left_flag} ${wheel_joint_z}"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel_func link_name="front_left" front_flag="1" left_flag="1"/>
    <xacro:wheel_func link_name="front_right" front_flag="1" left_flag="-1"/>
    <xacro:wheel_func link_name="back_left" front_flag="-1" left_flag="1"/>
    <xacro:wheel_func link_name="back_right" front_flag="-1" left_flag="-1"/>

    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
    
    <gazebo reference="front_left">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="front_right">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="back_left">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="back_right">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>