controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_arm_controller:
  ros__parameters:
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    gains:
      panda_joint1: {p: 50.0, i: 0.0, d: 20.0, ff_velocity_scale: 0.5}
      panda_joint2: {p: 5000.0, i: 0.0, d: 500.0, ff_velocity_scale: 0.5}
      panda_joint3: {p: 200.0, i: 1.7, d: 10.0, ff_velocity_scale: 0.5}
      panda_joint4: {p: 1000.0, i: 0.0, d: 50.0, ff_velocity_scale: 0.5}
      panda_joint5: {p: 100.0, i: 0.5, d: 10.0, ff_velocity_scale: 0.5}
      panda_joint6: {p: 100.0, i: 0.0, d: 10.0, ff_velocity_scale: 0.5}
      panda_joint7: {p: 10.0, i: 0.5, d: 0.1, ff_velocity_scale: 0.5}

panda_hand_controller:
  ros__parameters:
    command_interfaces: 
      - effort
    state_interfaces: 
      - position
      - effort
      - velocity
    joints: 
      - panda_finger_joint1
      - panda_finger_joint2
    allow_stalling: false
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    goal_tolerance: 0.01  
    max_effort: 500.0      
    gains:
      panda_finger_joint1: {p: 200.0, i: 0.0, d: 50.0}
      panda_finger_joint2: {p: 200.0, i: 0.0, d: 50.0}

