<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="lidar_radius" value="0.03"/>
    <xacro:property name="lidar_length" value="0.03"/>

    <xacro:property name="lidar_joint_x" value="${car_length/4}"/>
    <xacro:property name="lidar_joint_y" value="0"/>
    <xacro:property name="lidar_joint_z" value="${car_height / 2 + lidar_length / 2}"/>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.1 0.1 0.7 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/> <!-- 假设质量为0.2 kg，可根据实际情况调整 -->
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0002"/>
        </inertial>
    </link>
    <joint name="lidar_to_base_link" type="fixed">
        <parent link="base_link"/>
        <child link="lidar"/>
        <origin xyz="${lidar_joint_x} ${lidar_joint_y} ${lidar_joint_z}"/>
    </joint>

    <!-- Gazebo plugin for lidar sensor -->
    <gazebo reference="lidar">
        <sensor type="ray" name="lidar_sensor">
            <update_rate>62.0</update_rate>
            <visualize>true</visualize>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle> <!-- -90 degrees in radians -->
                        <max_angle>3.14159</max_angle>  <!-- 90 degrees in radians -->
                    </horizontal>
                </scan>
                <range>
                    <min>0.164</min>
                    <max>2.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_ray_sensor" filename="libgazebo_ros_ray_sensor.so">
                <topicName>/scan</topicName>
                <ros>
                    <remapping>~/out:=/scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
            </plugin>
        </sensor>
        <material>Gazebo/Blue</material>
    </gazebo>

</robot>