<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="lidar_radius" value="0.03"/>
    <xacro:property name="lidar_length" value="0.03"/>

    <xacro:property name="lidar_joint_x" value="${car_length/4}"/>
    <xacro:property name="lidar_joint_y" value="0"/>
    <xacro:property name="lidar_joint_z" value="${car_height / 2 + lidar_length / 2}"/>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.1 0.1 0.7 0.8"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/> <!-- 假设质量为0.2 kg，可根据实际情况调整 -->
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0002"/>
        </inertial>
    </link>
    <joint name="lidar_to_base_link" type="fixed">
        <parent link="base_link"/>
        <child link="lidar"/>
        <origin xyz="${lidar_joint_x} ${lidar_joint_y} ${lidar_joint_z}"/>
    </joint>

    <gazebo reference="lidar">
        <material>Gazebo/Blue</material>
    </gazebo>

</robot>